services:
  web:
    build: .
    ports:
      - "10000:10000"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=Asia/Manila
      - PORT=10000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
